### ISSUE TITLE
方案专用里86wubi配置文件五笔助记图顺序有误

### ISSUE THREAD

**Issue by Chengxcy** [cxcn/danjing#11]
'keys/@19/key_back_color': 86wb/K.png 
       'keys/@20/key_back_color': 86wb/L.png 
       'keys/@22/key_back_color': 86wb/Z.png 
       'keys/@24/key_back_color': 86wb/X.png 
       'keys/@23/key_back_color': 86wb/C.png 
       'keys/@25/key_back_color': 86wb/V.png

**Comment by nopdan** [comment]
没问题啊，你在哪儿看的

https://github.com/cxcn/danjing/blob/c0c99ef5a3ecf7f8f3633e43de2272d0f3c6bc96/%E6%96%B9%E6%A1%88%E4%B8%93%E7%94%A8/86%E4%BA%94%E7%AC%94/%E5%8D%95%E9%9D%99%2086%E4%BA%94%E7%AC%94.trime.yaml#L101

**Comment by Chengxcy** [comment]
2.5版本的适配列表里的86五笔助记![Screenshot_20230307-231843_GitHub.jpg](https://user-images.githubusercontent.com/91258009/223466028-6cff9ac8-5653-4bc1-9e9b-baaaab6cd620.jpg)

![Screenshot_20230307-231901_GitHub.jpg](https://user-images.githubusercontent.com/91258009/223466083-6a6a4511-95b8-4caa-a22d-0605af32e2b1.jpg)

**Comment by Chengxcy** [comment]
![Screenshot_20230307-232116_GitHub.jpg](https://user-images.githubusercontent.com/91258009/223466925-e0fe59fa-31c4-4c62-b63c-be7a53a6a97a.jpg)

https://github.com/cxcn/danjing/blob/6c1538a3a39db4c1163f53a42f086bf2b9001d73/方案专用/86五笔/单静%2086五笔.trime.yaml

**Comment by nopdan** [comment]
14f05d9f403f24867f1d7f8fc4b7efeac5c75594 修复过了
