### ISSUE TITLE
键宽度无法适应手机宽度问题

### ISSUE THREAD

**Issue by linkral** [cxcn/danjing#3]
配置主题键盘时，配置了一行可容纳28个键位，竖缝为1，按一行键总宽100分布下去，
最后一个键位总与屏幕最右边有间隙，增加了总键位宽度，最后一个键位又跳下一行，
请问此处如何能解决？

**Comment by nopdan** [comment]
宽度不支持小数点，没有很好的解决办法，可以考虑在每行开头增加空白 { width: 1 }，这样两边与屏幕间隙一致

**Comment by linkral** [comment]
> 宽度不支持小数点，没有很好的解决办法，可以考虑在每行开头增加空白 { width: 1 }，这样两边与屏幕间隙一致

原来问题点在这里，不支持小数点，两端加空白是个解决办法，那就把常用的几个键位加宽。
