### ISSUE TITLE
按键功能调整：长按设置键弹出主题菜单改为弹出输入法菜单

### ISSUE THREAD

**Issue by Kruegerrr** [cxcn/danjing#4]
在通常使用情景下，切换输入法比切换主题更加常用，例如在输入密码时希望快速切换到KeepassXC的密码键盘，在输入除汉语英语外的其他语言时切换到AnySoftKeyboard. 
现有方案切换输入法需要长按回车，然后点击二级菜单中的“输入法”，才能呼出系统输入法切换菜单，十分繁琐；相比之下，切换主题只需长按主键盘设置键（最下排左数第二个键）。为方便切换输入法，能否将长按主键盘设置键定义为弹出系统输入法选择菜单？

**Comment by nopdan** [comment]
你说的主题实际是配色吧，老版同文没有适配夜间模式，所以需要手动换配色，切换输入法我倒是没怎么用过，你觉得常用是个人习惯吧，又没有统计过。建议自己改一下就好。
