### ISSUE TITLE
要怎样使用这些文件啊？

### ISSUE THREAD

**Issue by SuWeipeng** [cxcn/danjing#6]

**Comment by SuWeipeng** [comment]
与 [https://github.com/SivanLaai/rime-pure](https://github.com/SivanLaai/rime-pure) 配合使用。安装方法见：[同文安卓端安装方法](http://www.sivanlaai.top/pages/7128fc/#%E5%90%8C%E6%96%87-%E5%AE%89%E5%8D%93%E7%AB%AF)

**Comment by nopdan** [comment]
暂时不支持九宫格
