### ISSUE TITLE
单静+主题如何修改默认键盘布局

### ISSUE THREAD

**Issue by ctrl-huangyq** [cxcn/danjing#9]
单静+主题中并没有`README`中提到的
```yaml
preset_keyboards:
  __include: danjing:/preset_keyboards
```
中的第二行。
我尝试在该位置下方及其他位置（如单静）中添加，但要么不生效，要么报循环依赖的错。
所以请问单静+主题可以如何修改配置文件以设置方案的默认键盘布局？

**Comment by nopdan** [comment]
一样的，在单静+ 中 `line 47` 下面添加。

**Comment by ctrl-huangyq** [comment]
感谢！这个问题貌似是同文v3.2.10的问题，回退到v3.2.9即可解决。
